apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: farouqu/udagram-api-feed:latest
          envFrom:
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
