apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: farouqu/udagram-api-user:latest
          envFrom:
            - secretRef:
                name: aws-secret
            - configMapRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
